language: ruby
rvm:
  - 2.5
  - 2.6
  - 2.7
  - 3.0
  - truffleruby
services:
  - redis
script:
  - bundle exec rspec spec

jobs:
  - language: ruby
    rvm: 2.7
    script:
      - bundle exec rubocop
